### PR TITLE
Laravel 9.0 Support

### PR DESCRIPTION
**Pull request by mpyw**
Laravel 9.0 is not released yet, so it is intended to create new unstable branch instead of merging to master.

### CODE REVIEW

**Comment by mpyw** [comment]
It seems that there are 2 problems:

- [CI result](https://github.com/staudenmeir/eloquent-eager-limit/runs/4202134714?check_suite_focus=true) represents that Postgres driver may have critical bug. Why don't we report or submit fixes on laravel/framework?
- Scrutinizer config seems to be outdated. Would you reconfigure it?

**Comment by staudenmeir** [comment]
Thanks, I've been working it. I'll get back to you.

**Comment by mpyw** [comment]
Related: https://github.com/laravel/framework/pull/39531

**Comment by staudenmeir** [comment]
I removed `laravel/homestead` and replaced `scrutinizer/ocular` with my own implementation.

With all the issues now fixed, I committed the Laravel 9 support to `master` (with you as the co-author) and it's available in Composer as `dev-master`.

**Pull request closed without merging**
